// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nexus-models.proto

/*
Package nexus is a generated protocol buffer package.

It is generated from these files:
	nexus-models.proto

It has these top-level messages:
	ProtoPin
	ProtoGroup
	GetGroupsResponse
	PutPinValueRequest
*/
package nexus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoPin struct {
	Board uint32 `protobuf:"varint,1,opt,name=board" json:"board,omitempty"`
	Id    uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *ProtoPin) Reset()                    { *m = ProtoPin{} }
func (m *ProtoPin) String() string            { return proto.CompactTextString(m) }
func (*ProtoPin) ProtoMessage()               {}
func (*ProtoPin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoPin) GetBoard() uint32 {
	if m != nil {
		return m.Board
	}
	return 0
}

func (m *ProtoPin) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProtoPin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProtoGroup struct {
	Name string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Pins []*ProtoPin `protobuf:"bytes,2,rep,name=pins" json:"pins,omitempty"`
}

func (m *ProtoGroup) Reset()                    { *m = ProtoGroup{} }
func (m *ProtoGroup) String() string            { return proto.CompactTextString(m) }
func (*ProtoGroup) ProtoMessage()               {}
func (*ProtoGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProtoGroup) GetPins() []*ProtoPin {
	if m != nil {
		return m.Pins
	}
	return nil
}

type GetGroupsResponse struct {
	Groups []*ProtoGroup `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (m *GetGroupsResponse) Reset()                    { *m = GetGroupsResponse{} }
func (m *GetGroupsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGroupsResponse) ProtoMessage()               {}
func (*GetGroupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetGroupsResponse) GetGroups() []*ProtoGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

type PutPinValueRequest struct {
	Board uint32 `protobuf:"varint,1,opt,name=board" json:"board,omitempty"`
	Id    uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Value int32  `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *PutPinValueRequest) Reset()                    { *m = PutPinValueRequest{} }
func (m *PutPinValueRequest) String() string            { return proto.CompactTextString(m) }
func (*PutPinValueRequest) ProtoMessage()               {}
func (*PutPinValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutPinValueRequest) GetBoard() uint32 {
	if m != nil {
		return m.Board
	}
	return 0
}

func (m *PutPinValueRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PutPinValueRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoPin)(nil), "nexus.ProtoPin")
	proto.RegisterType((*ProtoGroup)(nil), "nexus.ProtoGroup")
	proto.RegisterType((*GetGroupsResponse)(nil), "nexus.GetGroupsResponse")
	proto.RegisterType((*PutPinValueRequest)(nil), "nexus.PutPinValueRequest")
}

func init() { proto.RegisterFile("nexus-models.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0x3f, 0x4f, 0xc4, 0x30,
	0x0c, 0xc5, 0xd5, 0xbf, 0x02, 0x23, 0x40, 0xb5, 0x18, 0x3a, 0xa2, 0xb0, 0x94, 0x81, 0x0e, 0xb0,
	0x33, 0x81, 0xba, 0x46, 0x19, 0xd8, 0x5b, 0xd5, 0x42, 0x95, 0xda, 0x24, 0x34, 0x09, 0xe2, 0xe3,
	0x93, 0xba, 0x70, 0x77, 0xe3, 0x6d, 0x7e, 0x2f, 0xef, 0xfd, 0x2c, 0x07, 0x50, 0xd3, 0x4f, 0x70,
	0x4f, 0x8b, 0x19, 0x69, 0x76, 0xad, 0x5d, 0x8d, 0x37, 0x58, 0xb0, 0x27, 0xde, 0xe0, 0x42, 0x6e,
	0x5a, 0x4e, 0x1a, 0xef, 0xa0, 0x18, 0x4c, 0xbf, 0x8e, 0x75, 0x72, 0x9f, 0x34, 0xd7, 0x6a, 0x17,
	0x78, 0x03, 0xe9, 0x34, 0xd6, 0x29, 0x5b, 0x71, 0x42, 0x84, 0x5c, 0xf7, 0x0b, 0xd5, 0x59, 0x74,
	0x2e, 0x15, 0xcf, 0xe2, 0x1d, 0x80, 0x29, 0xdd, 0x6a, 0x82, 0x3d, 0x24, 0x92, 0x63, 0x02, 0x1f,
	0x20, 0xb7, 0x93, 0x76, 0x91, 0x93, 0x35, 0x57, 0xcf, 0xb7, 0x2d, 0x6f, 0x6f, 0xff, 0x57, 0x2b,
	0x7e, 0x14, 0xaf, 0x50, 0x75, 0xe4, 0x19, 0xe2, 0x14, 0x39, 0x6b, 0xb4, 0x23, 0x7c, 0x84, 0xf2,
	0x93, 0x9d, 0xc8, 0xdb, 0xba, 0xd5, 0x69, 0x97, 0xb3, 0xea, 0x2f, 0x20, 0x24, 0xa0, 0x0c, 0x3e,
	0xf2, 0x3e, 0xfa, 0x39, 0x90, 0xa2, 0xaf, 0x40, 0xce, 0x9f, 0x79, 0x56, 0x4c, 0x7d, 0x6f, 0x2d,
	0xbe, 0xab, 0x50, 0xbb, 0x18, 0x4a, 0xfe, 0xac, 0x97, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1,
	0x28, 0xdf, 0x78, 0x42, 0x01, 0x00, 0x00,
}
